FILTERS = {
    'rgb'          : 'Rgb',
    'rgba'         : 'Rgba',
    'grey'         : 'Greyscale',
    'hand_drawn'   : 'HandDrawn',
    'edge_curve'   : 'EdgeCurve',
    'blur'         : 'Blur',
    'contour'      : 'Contour',
    'edge_enhance' : 'EdgeEnhance',
    'emboss'       : 'Emboss',
    'smooth'       : 'Smooth',
    'sharpen'      : 'Sharpen',
    'gaussian_blur': 'GaussianBlur',
    'min'          : 'MinFilter',
    'median'       :'MedianFilter',
    'max'          : 'MaxFilter',
    'mode'         : 'ModeFilter',
    'unsharp_mask' : 'UnsharpMask',
    'emboss_45d'   : 'Emboss45d',
    'sharp_edge'   : 'SharpEdge',
    'sharp_center' : 'SharpCenter',
    'emboss_asym'  : 'EmbossAsymmetric',
    'dither'       : 'Dither',
    'hsv'          : 'Hsv',    
}